//===--------------- HelperFileNames.inc ----------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

HELPERFILE(dpct.hpp.inc, dpct.hpp, Dpct)
HELPERFILE(device.hpp.inc, device.hpp, Device)
HELPERFILE(kernel.hpp.inc, kernel.hpp, Kernel)
HELPERFILE(math.hpp.inc, math.hpp, Math)
HELPERFILE(memory.hpp.inc, memory.hpp, Memory)
HELPERFILE(util.hpp.inc, util.hpp, Util)
HELPERFILE(dpl_utils.hpp.inc, dpl_utils.hpp, DplUtils)
HELPERFILE(blas_utils.hpp.inc, blas_utils.hpp, BlasUtils)
HELPERFILE(dnnl_utils.hpp.inc, dnnl_utils.hpp, DnnlUtils)
HELPERFILE(image.hpp.inc, image.hpp, Image)
HELPERFILE(atomic.hpp.inc, atomic.hpp, Atomic)
HELPERFILE(rng_utils.hpp.inc, rng_utils.hpp, RngUtils)
HELPERFILE(lib_common_utils.hpp.inc, lib_common_utils.hpp, LibCommonUtils)
HELPERFILE(ccl_utils.hpp.inc, ccl_utils.hpp, CclUtils)
HELPERFILE(sparse_utils.hpp.inc, sparse_utils.hpp, SparseUtils)
HELPERFILE(fft_utils.hpp.inc, fft_utils.hpp, FftUtils)
HELPERFILE(lapack_utils.hpp.inc, lapack_utils.hpp, LapackUtils)
HELPERFILE(dpl_extras/algorithm.h.inc, algorithm.h, DplExtrasAlgorithm)
HELPERFILE(dpl_extras/functional.h.inc, functional.h, DplExtrasFunctional)
HELPERFILE(dpl_extras/iterators.h.inc, iterators.h, DplExtrasIterators)
HELPERFILE(dpl_extras/memory.h.inc, memory.h, DplExtrasMemory)
HELPERFILE(dpl_extras/numeric.h.inc, numeric.h, DplExtrasNumeric)
HELPERFILE(dpl_extras/vector.h.inc, vector.h, DplExtrasVector)
HELPERFILE(dpl_extras/dpcpp_extensions.h.inc, dpcpp_extensions.h, DplExtrasDpcppExtensions)
