//===---HelperFileNames.inc-------------------------------------------===//
//
// Copyright (C) 2021 Intel Corporation. All rights reserved.
//
// The information and source code contained herein is the exclusive
// property of Intel Corporation and may not be disclosed, examined
// or reproduced in whole or in part without explicit written authorization
// from the company.
//
//===-----------------------------------------------------------------===//

HELPERFILE(dpct.hpp.inc, Dpct)
HELPERFILE(device.hpp.inc, Device)
HELPERFILE(kernel.hpp.inc, Kernel)
HELPERFILE(memory.hpp.inc, Memory)
HELPERFILE(util.hpp.inc, Util)
HELPERFILE(dpl_utils.hpp.inc, DplUtils)
HELPERFILE(blas_utils.hpp.inc, BlasUtils)
HELPERFILE(image.hpp.inc, Image)
HELPERFILE(atomic.hpp.inc, Atomic)
HELPERFILE(dpl_extras/algorithm.h.inc, DplExtrasAlgorithm)
HELPERFILE(dpl_extras/functional.h.inc, DplExtrasFunctional)
HELPERFILE(dpl_extras/iterators.h.inc, DplExtrasIterators)
HELPERFILE(dpl_extras/memory.h.inc, DplExtrasMemory)
HELPERFILE(dpl_extras/numeric.h.inc, DplExtrasNumeric)
HELPERFILE(dpl_extras/vector.h.inc, DplExtrasVector)
