//===---DiagnosticsBuildScript.inc------------------------------------===//
//
// Copyright (C) Intel Corporation. All rights reserved.
//
// The information and source code contained herein is the exclusive
// property of Intel Corporation and may not be disclosed, examined
// or reproduced in whole or in part without explicit written authorization
// from the company.
//
//===-----------------------------------------------------------------===//

// FORMAT: {NAME, ID, MESSAGE}
DEF_COMMENT(GEN_MAKEFILE_LIB, 2001, "You can link with more library by add them here.")
DEF_COMMENT(GEN_MAKEFILE_OPT, 2002, "You can change different compiler optimization options here.")
