//===--------------- APINamesMemberExprCUB.inc -------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

MEM_EXPR_ENTRY("cub::DoubleBuffer.d_buffers", MEM_BASE, LITERAL("iter"))

MEM_EXPR_ENTRY("cub::DoubleBuffer.Current", MEM_BASE, LITERAL("first"))

MEM_EXPR_ENTRY("cub::DoubleBuffer.Alternate", MEM_BASE, LITERAL("second"))
