//===--------------------- APINamesNvtx.inc -------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

REMOVE_API_FACTORY_ENTRY_WITH_MSG("nvtxNameCudaStreamA", "NVTX API is for debugging purposes only.")
REMOVE_API_FACTORY_ENTRY_WITH_MSG("nvtxRangePushA", "NVTX API is for debugging purposes only.")
REMOVE_API_FACTORY_ENTRY_WITH_MSG("nvtxRangePushW", "NVTX API is for debugging purposes only.")
REMOVE_API_FACTORY_ENTRY_WITH_MSG("nvtxRangePop", "NVTX API is for debugging purposes only.")
