//===--------------------- APINamesNvtx.inc -------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

REMOVE_API_FACTORY_ENTRY_WITH_MSG(
    "nvtxNameCudaStreamA",
    "it annotates source code to provide contextual information to the CUDA "
    "analysis tool. Consider using Intel(R) Instrumentation and Tracing "
    "Technology (ITT) API to implement a similar function.")
REMOVE_API_FACTORY_ENTRY_WITH_MSG(
    "nvtxRangePushA",
    "it annotates source code to provide contextual information to the CUDA "
    "analysis tool. Consider using Intel(R) Instrumentation and Tracing "
    "Technology (ITT) API to implement a similar function.")
REMOVE_API_FACTORY_ENTRY_WITH_MSG(
    "nvtxRangePushW",
    "it annotates source code to provide contextual information to the CUDA "
    "analysis tool. Consider using Intel(R) Instrumentation and Tracing "
    "Technology (ITT) API to implement a similar function.")
REMOVE_API_FACTORY_ENTRY_WITH_MSG(
    "nvtxRangePop",
    "it annotates source code to provide contextual information to the CUDA "
    "analysis tool. Consider using Intel(R) Instrumentation and Tracing "
    "Technology (ITT) API to implement a similar function.")
