// UNSUPPORTED: system-windows
// intercept-build not found on windows
//
// ------ prepare test directory
// RUN: cd %T
// RUN: rm -rf gen-build-script
// RUN: mkdir  gen-build-script
// RUN: cd     gen-build-script
// RUN: cp %s gen-build-script.cpp
//
// ------ create makefile
// RUN: echo "gen-build-script.o      :       gen-build-script.cpp                                                                  "      >  Makefile
// RUN: echo "	%clangxx -c gen-build-script.cpp -DFOOBAR -msse4.1 -mavx512vl -O2 -isystem %cuda-path/include -I %cuda-path/include "      >> Makefile
//
// ------ create compilation database
// RUN: intercept-build make -f Makefile
//
// ------ Use --gen-build-script to generate makefile
//        The 'not' prefix is used to invert the dpct return code, and thus prevent a LIT failure.
//        dpct returns non-zero because input has no CUDA code, but the return-code can be ignored
//        because the code is not relevant to this testcase.
// RUN: not dpct -p ./ -out-root=out --gen-build-script --cuda-include-path="%cuda-path/include"
//
// ------ ensure that '-msse4.1' and '-mavx512vl' options are in makefile generated by dpct
// RUN: FileCheck --input-file out/Makefile.dpct %s
//
// ------ cleanup test directory
// RUN: cd ..
// RUN: rm -rf ./gen-build-script

// CHECK: -DFOOBAR -msse4.1 -mavx512vl -O2

void foo() {
}
