//===--------------- DiagnosticsBuildScript.inc ---------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

// FORMAT: {NAME, ID, MESSAGE}
DEF_COMMENT(GEN_MAKEFILE_LIB, 2001, "You can link with more libraries by adding them here.")
DEF_COMMENT(GEN_MAKEFILE_OPT, 2002, "You can change different compiler optimization options here.")
