//===--------------- TextModificationKind.inc ----------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
TRANSFORMATION(ReplaceStmt)
TRANSFORMATION(ReplaceDecl)
TRANSFORMATION(ReplaceCalleeName)
TRANSFORMATION(ReplaceTypeInDecl)
TRANSFORMATION(ReplaceVarDecl)
TRANSFORMATION(ReplaceReturnType)
TRANSFORMATION(ReplaceToken)
TRANSFORMATION(InsertText)
TRANSFORMATION(ReplaceCCast)
TRANSFORMATION(RenameFieldInMemberExpr)
TRANSFORMATION(InsertAfterStmt)
TRANSFORMATION(ReplaceInclude)
TRANSFORMATION(ReplaceDim3Ctor)
TRANSFORMATION(InsertComment)
TRANSFORMATION(InsertBeforeCtrInitList)
TRANSFORMATION(InsertBeforeStmt)
TRANSFORMATION(RemoveArg)
TRANSFORMATION(InsertClassName)
TRANSFORMATION(ReplaceText)
