//===---Transformations.inc------------------------------------------===//
//
// Copyright (C) 2018 - 2020 Intel Corporation. All rights reserved.
//
// The information and source code contained herein is the exclusive
// property of Intel Corporation and may not be disclosed, examined
// or reproduced in whole or in part without explicit written authorization
// from the company.
//
//===-----------------------------------------------------------------===//
TRANSFORMATION(ReplaceStmt)
TRANSFORMATION(ReplaceCalleeName)
TRANSFORMATION(RemoveAttr)
TRANSFORMATION(ReplaceTypeInDecl)
TRANSFORMATION(ReplaceVarDecl)
TRANSFORMATION(ReplaceReturnType)
TRANSFORMATION(ReplaceToken)
TRANSFORMATION(InsertText)
TRANSFORMATION(ReplaceCCast)
TRANSFORMATION(RenameFieldInMemberExpr)
TRANSFORMATION(InsertAfterStmt)
TRANSFORMATION(ReplaceInclude)
TRANSFORMATION(ReplaceDim3Ctor)
TRANSFORMATION(InsertComment)
TRANSFORMATION(InsertBeforeCtrInitList)
TRANSFORMATION(InsertBeforeStmt)
TRANSFORMATION(RemoveArg)
TRANSFORMATION(InsertClassName)
TRANSFORMATION(ReplaceText)
