// Single Precision Mathematical Functions
ENTRY("frexpf", "cl::sycl::frexp")
ENTRY("modff", "cl::sycl::modf")
ENTRY("nanf", "cl::sycl::nan")
ENTRY("nearbyintf", "cl::sycl::floor")
ENTRY("remquof", "cl::sycl::remquo")
ENTRY("rhypotf", "cl::sycl::hypot")
ENTRY("sincosf", "cl::sycl::sincos")
ENTRY("sincospif", "cl::sycl::sincos")
ENTRY("__sincosf", "cl::sycl::sincos")

// Double Precision Mathematical Functions
ENTRY("frexp", "cl::sycl::frexp")
ENTRY("modf", "cl::sycl::modf")
ENTRY("nan", "cl::sycl::nan")
ENTRY("nearbyint", "cl::sycl::floor")
ENTRY("remquo", "cl::sycl::remquo")
ENTRY("rhypot", "cl::sycl::hypot")
ENTRY("sincos", "cl::sycl::sincos")
ENTRY("sincospi", "cl::sycl::sincos")

