// Half/Half2 Arithmetic Functions
ENTRY_DIV("__h2div")
ENTRY_DIV("__hdiv")

ENTRY_MUL("__hmul")
ENTRY_MUL("__hmul2")


ENTRY_SUB("__hsub")
ENTRY_SUB("__hsub2")

ENTRY_SUB("__hneg")
ENTRY_SUB("__hneg2")

// Half Comparison Functions
ENTRY_EQ("__heq")
ENTRY_NE("__hne")
ENTRY_GE("__hge")
ENTRY_GT("__hgt")
ENTRY_LE("__hle")
ENTRY_LT("__hlt")

// Single Precision Mathematical Functions
ENTRY_ADD("__fadd_rd")
ENTRY_ADD("__fadd_rn")
ENTRY_ADD("__fadd_ru")
ENTRY_ADD("__fadd_rz")
ENTRY_SUB("__fsub_rd")
ENTRY_SUB("__fsub_rn")
ENTRY_SUB("__fsub_ru")
ENTRY_SUB("__fsub_rz")
ENTRY_MUL("__fmul_rd")
ENTRY_MUL("__fmul_rn")
ENTRY_MUL("__fmul_ru")
ENTRY_MUL("__fmul_rz")
ENTRY_DIV("__fdiv_rd")
ENTRY_DIV("__fdiv_rn")
ENTRY_DIV("__fdiv_ru")
ENTRY_DIV("__fdiv_rz")

// Double precision intrinisics
ENTRY_ADD("__dadd_rd")
ENTRY_ADD("__dadd_rn")
ENTRY_ADD("__dadd_ru")
ENTRY_ADD("__dadd_rz")
ENTRY_SUB("__dsub_rd")
ENTRY_SUB("__dsub_rn")
ENTRY_SUB("__dsub_ru")
ENTRY_SUB("__dsub_rz")
ENTRY_MUL("__dmul_rd")
ENTRY_MUL("__dmul_rn")
ENTRY_MUL("__dmul_ru")
ENTRY_MUL("__dmul_rz")
ENTRY_DIV("__ddiv_rd")
ENTRY_DIV("__ddiv_rn")
ENTRY_DIV("__ddiv_ru")
ENTRY_DIV("__ddiv_rz")
